"""Render ScanResult as GitHub-flavored Markdown."""

from __future__ import annotations

from io import StringIO

from reconfox.models import ScanResult


def render_markdown(result: ScanResult) -> str:
    buf = StringIO()
    _header(buf, result)
    _target_block(buf, result)
    _ports_block(buf, result)
    _web_block(buf, result)
    _vuln_block(buf, result)
    _errors_block(buf, result)
    _footer(buf, result)
    return buf.getvalue()


def _header(buf: StringIO, result: ScanResult) -> None:
    buf.write("# reconfox report\n\n")
    buf.write(f"**Target:** `{result.target.url}`  \n")
    buf.write(f"**Mode:** `{result.mode.value}`  \n")
    buf.write(f"**Status:** `{result.status.value}`  \n")
    buf.write(f"**Started:** {result.started_at.isoformat()}  \n")
    if result.duration_seconds is not None:
        buf.write(f"**Duration:** {result.duration_seconds:.0f} s  \n")
    buf.write("\n---\n\n")


def _target_block(buf: StringIO, result: ScanResult) -> None:
    t = result.target
    buf.write("## Цель\n\n")
    buf.write("| Поле | Значение |\n|---|---|\n")
    buf.write(f"| Hostname | `{t.hostname}` |\n")
    buf.write(f"| IP | `{t.ip or '—'}` |\n")
    buf.write(f"| Port | {t.port} |\n")
    buf.write(f"| HTTPS | {'да' if t.is_https else 'нет'} |\n")
    if t.asn:
        asn_str = f"AS{t.asn.asn} {t.asn.asn_name or ''}".strip()
        buf.write(f"| ASN | {asn_str} |\n")
        if t.asn.isp:
            buf.write(f"| ISP | {t.asn.isp} |\n")
    if t.geo:
        loc = ", ".join(filter(None, [t.geo.city, t.geo.region, t.geo.country]))
        if loc:
            buf.write(f"| Локация | {loc} |\n")
    buf.write("\n")


def _ports_block(buf: StringIO, result: ScanResult) -> None:
    if not result.ports:
        return
    buf.write("## Открытые порты\n\n")
    buf.write("| Порт | Proto | State | Service | Product | Version |\n")
    buf.write("|---|---|---|---|---|---|\n")
    for p in sorted(result.ports, key=lambda x: x.port):
        buf.write(
            f"| {p.port} | {p.protocol} | {p.state} | "
            f"{p.service or '—'} | {p.product or '—'} | {p.version or '—'} |\n"
        )
    buf.write("\n")


def _web_block(buf: StringIO, result: ScanResult) -> None:
    if not result.web_findings:
        return
    buf.write("## Веб-находки\n\n")
    buf.write("| URL | Status | Length | Redirect |\n|---|---|---|---|\n")
    for f in result.web_findings:
        buf.write(
            f"| `{f.url}` | {f.status} | {f.length} | "
            f"{f.redirect or '—'} |\n"
        )
    buf.write("\n")


def _vuln_block(buf: StringIO, result: ScanResult) -> None:
    if not result.vulnerabilities:
        return
    buf.write("## Уязвимости\n\n")
    by_sev = sorted(result.vulnerabilities, key=lambda v: -v.severity.score)
    for v in by_sev:
        port_info = f" (порт {v.affected_port})" if v.affected_port else ""
        cve_info = f" — {v.cve}" if v.cve else ""
        buf.write(f"### [{v.severity.value.upper()}] {v.title}{cve_info}{port_info}\n\n")
        buf.write(f"- **Источник:** {v.source}\n")
        if v.description:
            buf.write(f"- **Описание:** {v.description}\n")
        if v.metasploit_module:
            buf.write(f"- **Metasploit:** `{v.metasploit_module}`\n")
        if v.exploit_path:
            buf.write(f"- **Exploit:** `{v.exploit_path}`\n")
        for ref in v.references:
            buf.write(f"- {ref}\n")
        buf.write("\n")


def _errors_block(buf: StringIO, result: ScanResult) -> None:
    if not result.errors:
        return
    buf.write("## Ошибки\n\n")
    for err in result.errors:
        buf.write(f"- `{err}`\n")
    buf.write("\n")


def _footer(buf: StringIO, result: ScanResult) -> None:
    buf.write("---\n\n")
    buf.write("_Generated by [reconfox](https://github.com/kovanZ1/reconfox)._\n")
    if result.finished_at:
        buf.write(f"_Finished at: {result.finished_at.isoformat()}_\n")
